Add Lighthouse CI (#24)
* Update main.yml

* Update main.yml

* Update main.yml

* Create lighthouserc.js

* Prettified Code!

* Update main.yml

* Update lighthouserc.js

* Prettified Code!

* Update lighthouserc.js

* Update Config Again

* Switch to Netlify-based Test

* Wait for build to finish before running lighthouse

* Fix deploy url

Co-authored-by: jhthenerd <jhthenerd@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,7 +5,7 @@ on:
   pull_request:
   push:
     branches:
-    - master
+      - master
   repository_dispatch:
     types: [airtable]
 
@@ -14,57 +14,72 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Repo
-      uses: actions/checkout@v2
-      with:
-        # Make sure the actual branch is checked out when running on pull requests
-        ref: ${{ github.head_ref }}
+      - name: Checkout Repo
+        uses: actions/checkout@v2
+        with:
+          # Make sure the actual branch is checked out when running on pull requests
+          ref: ${{ github.head_ref }}
 
-    - name: Prettify Code
-      uses: creyD/prettier_action@v3.0
-      with:
-        # This part is also where you can pass other options, for example:
-        prettier_options: --write **/*.{js,md}
+      - name: Prettify Code
+        uses: creyD/prettier_action@v3.0
+        with:
+          # This part is also where you can pass other options, for example:
+          prettier_options: --write **/*.{js,md}
 
   build:
-    needs: [prettier]
     runs-on: ubuntu-latest
-    
+    outputs:
+      deploy-url: ${{ steps.netlify-deploy.outputs.deploy-url }}
     steps:
-    - name: Checkout Repo
-      uses: actions/checkout@v2
-      with:
-        # Make sure the actual branch is checked out when running on pull requests
-        ref: ${{ github.head_ref }}
+      - name: Checkout Repo
+        uses: actions/checkout@v2
+        with:
+          # Make sure the actual branch is checked out when running on pull requests
+          ref: ${{ github.head_ref }}
 
-    - name: Cache node_modules
-      id: cache-node-modules
-      uses: actions/cache@v1
-      with:
-        path: node_modules
-        key: ${{ runner.os }}-build-npm-${{ hashFiles('**/package-lock.json') }}
-        restore-keys: |
-          ${{ runner.os }}-build-npm-
-      
-    - name: Install Dependencies
-      if: steps.cache-node-modules.outputs.cache-hit != 'true'
-      run: npm install
+      - name: Cache node_modules
+        id: cache-node-modules
+        uses: actions/cache@v1
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-build-npm-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-npm-
 
-    - name: Build Static Files
-      run: npm run build
-      env:
-        AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
-        BASE_ID: ${{ secrets.BASE_ID }}
-        LOCATIONIQ: ${{ secrets.LOCATIONIQ }}
-    
-    - name: Deploy to Netlify
-      uses: nwtgck/actions-netlify@v1.1.2
-      with:
-        # Publish directory
-        publish-dir: './public'
-        production-branch: master
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        deploy-message: "Deploy from GitHub Actions"
-      env:
+      - name: Install Dependencies
+        if: steps.cache-node-modules.outputs.cache-hit != 'true'
+        run: npm install
+
+      - name: Build Site
+        run: npm run build
+        env:
+          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
+          BASE_ID: ${{ secrets.BASE_ID }}
+          LOCATIONIQ: ${{ secrets.LOCATIONIQ }}
+
+      - name: Deploy to Netlify
+        id: netlify-deploy
+        uses: nwtgck/actions-netlify@v1.1.2
+        with:
+          # Publish directory
+          publish-dir: "./public"
+          production-branch: master
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          deploy-message: "Deploy from GitHub Actions"
+        env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
+
+  lighthouse:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Setup Node.js
+        uses: actions/setup-node@v1
+        
+      - name: Run Lighthouse Tests
+        run: |
+          npm install -g @lhci/cli@0.4.x
+          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ needs.build.outputs.deploy-url }} || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
